### ISSUE TITLE
How to run this code to execute on a blob of data?

### ISSUE THREAD

**Issue by vrajbillings** [pgodwin/OcfLzw#5]
Hi @pgodwin

Thank you for the execution of OCFLZW @pgodwin 
I was wondering if you had a readme file which could tell me how to run this code against a piece of blob data?

**Comment by vrajbillings** [comment]
So i started running the unit tests [here ](https://github.com/pgodwin/OcfLzw/blob/master/DecodeTesting/UnitTest1.cs#L13)and it explains a possible way of decoding the values but wanted to check how did you obtain            
` var base64Value = @"PZcOR0MwxLhhNxzNMIhRpMZwM4xGQ1GRcMhlMxmGEXjJshMSGAzGcCMxvNx0OhiNkljhmNxpNhcMxjNBhORzMp0GAgKhhNBvNphHZ9PoNBRcOxpMp3NZpNxkGhcOpjg5wm5kmcuOYynhlORyN5yLlXOVHowKgIAAAG9jZl9ibG9iAA==";
` 
Did you apply any typecasting on the blob_contents? just wanted to check how you obtained that base64Value to decode to text.
for example did you do? `select UTL_RAW.CAST_TO_RAW(UTL_RAW.CAST_TO_VARCHAR2(BLOB_CONTENTS)) From CE_BLOB`

**Comment by pgodwin** [comment]
Hi @vrajbillings 

I honestly don't recall, but something like what you have would do the job (I'm using SQL Server rather than Oracle).

It's designed to be used really directly with either the output saved to disk, with a `DataReader` or as part of a SQL Server CLR. The library `Decode()` method accepts either `byte[]` or an input and output `Stream` (technically it supports string, but assumes 8-bit `char` values, so you're better off using `byte[]` or `Stream`). 

So, I guess in your example, there's no need to cast anything, just get a connection to your DB, create a datareader for a select statement and pass the blob straight to the library either as an `OracleStream` or a `byte[]`.

**Comment by vrajbillings** [comment]
Thanks @pgodwin i got this to work. Follow up question: You mentioned it is designed to work with output saved to a disk. I am curious to know how much time does it take to save that output to disk. Current if i query against the ce_blob table for saving 10k records it takes approximately 7-8 minutes. Is there a better way of taking out blob data from cerner's table?

**Comment by pgodwin** [comment]
I use it as part of an ETL, I don't actually write them out to disk.

I'm not sure why you're seeing such poor performance. It might be worth talking with your DBA's about. If you're accessing it over a slow connection, you might be seeing high latency too. Assuming you're using the Oracle client, there's a few parameters around chunk-size and prefetching that might help.
